name: C/C++ CI

on: [push, pull_request]

jobs:
  Cars:

    runs-on: [ubuntu-20.04]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: mkdir build
      run: mkdir build
    - name: Compile
      working-directory: build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: build
      run: ctest -V 
    - name: Run Valgrind
      working-directory: build
      run: |
          sudo apt-get update -y    
          sudo apt-get install -y valgrind
          valgrind --leak-check=yes ./ElectricCar-ut
          valgrind --leak-check=yes ./HybridCar-ut
          valgrind --leak-check=yes ./PetrolCar-ut
